dataset:
  defense_transforms:
    - name: ColorJitter
      args:
        brightness: 0.4
        contrast: 0.4
        saturation: 0.4
        hue: 0.25
    - name: CenterCrop
      args:
        size: 24
    - name: Pad
      args:
        padding: 4
    - name: ToTensor