eval:
  adv_images_dir: ${path:adv_images/adv_images-8/}
  model:
    name: Ensemble
    models:
      - nin
      - resnet20
      - sepreresnet56
      - densenet40_k12_bc
      - diaresnet110
attack:
  method: pgd
  iters:
    type: fixed
    args: 8
