dataset:
  dataset_root: ${path:data}
  transforms:
    - name: ToTensor
  defense_transforms:
    - name: ToTensor
attack:
  method: pgd
  args:
    epsilon: 0.03125
  iters:
    type: fixed
    args: 1
  freq:
    type: fixed
    args: 1

misc:
  batch_size: 1
  num_workers: 1
  checkpoint_period: 100
