dataset:
  dataset_root: ${path:data}
  transforms:
    - name: ToTensor
  defense_transforms:
    - name: ToTensor
attack:
  method: pgd
  args:
    alpha: 0.015625
    epsilon: 0.03125
  iters:
    type: fixed
    args: 8
  freq:
    type: fixed
    args: 8
misc:
  batch_size: 128
  num_workers: 8
  checkpoint_period: 10
