dataset:
  dataset_root: ${path:data}
  transforms:
    - name: ToTensor
  defense_transforms:
    - name: ToTensor
attack:
  method: pgd
  num_iters: 1
  epsilon: 0.03125
misc:
  batch_size: 1
  num_workers: 1
  checkpoint_period: 100
  adversarial_examples_resample_period: 100
