recorder_root: ${path:logs/densent40-k12-adversarial-training}
model_name: densenet40_k12
attack:
  method: pgd
  num_iters: 10
optimizer:
  name: SGD
  lr: 0.0005
  scheduler:
    name: CyclicLR
    type: batch
    base_lr: 0.00001
    max_lr: 0.0005
misc:
  num_epochs: 200
  batch_size: 128
  num_workers: 16
  checkpoint_period: 10
  adversarial_examples_resample_period: 10
