attack:
  method: pgd
  num_iters: 16
optimizer:
  name: SGD
  lr: 0.0005
  scheduler:
    name: CyclicLR
    type: batch
    base_lr: 0.00001
    max_lr: 0.0005
misc:
  num_epochs: 256
  batch_size: 128
  num_workers: 8
  checkpoint_period: 8
  adversarial_examples_resample_period: 16
